#ci
version: "3.9"

services:
  vote-app-mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql:/var/lib/mysql:delegated
      - ./db_assets:/docker-entrypoint-initdb.d/:delegated
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
    security_opt:
      - no-new-privileges:true
    networks:
      - ci-net
  
  backend-part:
    image: alonimacaroni/vote-backend:ci
    restart: unless-stopped
    volumes:
      - ./vote_app_backend:/code
    command: >
      sh -c 'gunicorn vote_app_backend.wsgi:application --bind :8000'
    env_file:
      - .env
    environment:
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASS=${MYSQL_PASSWORD}
      - DATABASE_HOST=${MYSQL_HOST}
      - DATABASE_PORT=${MYSQL_PORT}
      - URI_ENTRYP_PATH=${URI_ENTRYP_PATH}
      - URI_CSRF_PATH=${URI_CSRF_PATH}
      - DOMAIN_URL=${DOMAIN_URL}
    security_opt:
      - no-new-privileges:true
    depends_on:
      - vote-app-mysql
    networks:
      - ci-net

networks:
  ci-net:
    driver: bridge

volumes:
  mysql:
    driver: local