#ci
version: "3.9"

services:
  vote-app-mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql:delegated
      - ./db_assets:/docker-entrypoint-initdb.d/:delegated
#copy mysql config in running container
#list containers
#docker ps -aqf "name=^janina-voting-app_vote-app-mysql"
#put upper command in second command (test):
    command: >
      sh -c 'docker ps -aqf "name=^janina-voting-app_vote-app-mysql" | xargs -I{} docker cp ./db_assets/mysqld.cnf {}:/var/lib/mysql/' 
    # command: >
    #   sh -c 'docker cp ./db_assets/mysqld.cnf janina-voting-app_vote-app-mysql_1:/var/lib/mysql/'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=vote-app-mysql
      #- MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
    security_opt:
      - no-new-privileges:true
  
  backend-part:
    image: alonimacaroni/vote-backend:ci
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./vote_app_backend:/code
    command: >
      sh -c 'gunicorn vote_app_backend.wsgi:application --bind ${DOMAIN_URL}:8000'
    environment:
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASS=${MYSQL_PASSWORD}
      - MYSQL_HOST=vote-app-mysql
      #- DATABASE_HOST=${MYSQL_HOST}
      - DATABASE_PORT=${MYSQL_PORT}
      - URI_ENTRYP_PATH=${URI_ENTRYP_PATH}
      - URI_CSRF_PATH=${URI_CSRF_PATH}
      - DOMAIN_URL=${DOMAIN_URL}
    security_opt:
      - no-new-privileges:true
    depends_on:
      - vote-app-mysql

volumes:
  mysql:
    driver: local