version: "3"

services:
  frontend-part:
    image: alonimacaroni/vote-frontend:latest
    restart: always
    volumes:
      - ./frontend-ui:/app
    ports:
      - "8080:8080"
    command: >
      sh -c 'npm run serve'
    networks:
      - frontend
  vote-app-mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks: 
      - backend
  backend-part:
    image: alonimacaroni/vote-backend:latest
    restart: always
    volumes:
      - ./vote_app_backend:/code
    ports:
      - "8000:8000"
    command: >
      sh -c 'python manage.py runserver 0:8000'
    environment:
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASS=${MYSQL_PASSWORD}
    networks:
      - backend
      - frontend
    depends_on:
      - vote-app-mysql

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  mysql:
    driver: local