version: "3"

services:
  frontend-part:
    image: alonimacaroni/vote-frontend:latest
    restart: always
    ports:
      - "8080:8080"
  vote-app-mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
    - "3302:3306"
    command: >
      sh -c 'mysql &&
             GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root' WITH GRANT OPTION;'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  backend-part:
    image: alonimacaroni/vote-backend:latest
    restart: always
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    command: >
      sh -c 'python vote_app_backend/manage.py runserver 8000'
    environment:
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASS=${MYSQL_PASSWORD}
    depends_on:
      - vote-app-mysql


volumes:
  mysql:
    driver: local