#local
version: "3.9"


services:
  frontend-part:
    image: alonimacaroni/vote-frontend:latest
    labels: 
      #turn on traefik monitoring: enable traefik to recognize changes in the label configurations in the container
      - "traefik.enable=true"
#      - "traefik.port=80"
#      - "traefik.docker.network=proxy"
      - "traefik.http.routers.frontend-part.entrypoints=web"
#, websecure
      - "traefik.http.routers.frontend-part.rule=Host(`janina.test`, `www.janina.test`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=80"
      #obtain trusted SSL certificate
      - "traefik.http.routers.frontent-part.tls=false"
      - "traefik.default.protocol=http"
      #traefik.http.routers.frontend-part.tls.certresolver: myresolver
      #traefik.http.routers.frontend-part-http.middlewares: force-https
    restart: unless-stopped
    volumes:
      - ./frontend-ui:/app
    #don't use run serve on server
    command: >
      sh -c 'npm run serve'
    environment:
      - VUE_APP_URI_ENTRYP_PATH=${URI_ENTRYP_PATH}
      - VUE_APP_URI_CSRF_PATH=${URI_CSRF_PATH}
      - VUE_APP_DOMAIN_URL=${DOMAIN_URL}
    ports:
      - "8080:8080"
    networks:
      - proxy
  vote-app-mysql:
    image: mysql:8.0
    labels: 
      - "traefik.enable=true"
#      - "traefik.port=80"
#      - "traefik.docker.network=proxy"
      - "traefik.http.services.traefik.loadbalancer.server.port=80"
      - "traefik.default.protocol=http"
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql:delegated
      - ./db_assets:/docker-entrypoint-initdb.d/:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks: 
      - proxy
  backend-part:
    image: alonimacaroni/vote-backend:latest
    labels: 
      - "traefik.enable=true"
#      - "traefik.port=80"
#     - "traefik.docker.network=proxy"
      - "traefik.http.routers.backend-part.entrypoints=web"
#, websecure
      - "traefik.http.routers.backend-part.rule=Host(`janina.test`, `www.janina.test`) && PathPrefix(`/api/`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=80"
      - "traefik.http.routers.backend-part.tls=false"
      - "traefik.default.protocol=http"
      #for letsencrypt
      #traefik.http.routers.backend-part.tls.certresolver: myresolver 
      #traefik.http.routers.backend-part-http.middlewares: force-https
    restart: unless-stopped
    volumes:
      - ./vote_app_backend:/code
    command: >
      sh -c 'python manage.py runserver 0:8000'
    environment:
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASS=${MYSQL_PASSWORD}
      - URI_ENTRYP_PATH=${URI_ENTRYP_PATH}
      - URI_CSRF_PATH=${URI_CSRF_PATH}
      - DOMAIN_URL=${DOMAIN_URL}
    ports:
      - "8000:8000"
    networks:
      - proxy
    depends_on:
      - vote-app-mysql
  proxy-part:
    image: traefik:v2.7
    restart: unless-stopped
    #static configuration
    command: 
      - --global.sendanonymoususage=false
      #for debugging
      - --log.level=DEBUG
#formatbezeichnung richtig?
      #- "--log.format=json"
#dateiendung richtig?
      #- "--log.filePath=/var/log/traefik/traefik.json"
      #enable dashboard
      - --api.dashboard=true
      - --api.insecure=true
      #- "--providers.docker.endpoint=unix:///var/run/docker.sock"
      #- "--providers.docker.watch=true"
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      #redirection to HTTPS
      #- "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      #in order to use https locally you still need a CA
#      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
#      - "--entrypoints.web-secure.address=:443"
      #settings for mkcert, self-signed certs should be used locally (not letsencrypt)
      #letsencrypt needs to establish a connection via the http challenge
      #mkcert creates a cert and installs a CA locally
      #certificateresolver is only needed with letsencrypt
      # - "--certificatesResolvers.myresolver.acme.email=schroeder@convidera.com"
      # - "--certificatesResolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # - "--certificatesResolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      # - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web"
      #traefik.http.routers.proxy-part.entrypoint: web
      #traefik.http.routers.proxy-part.entrypoint.to: websecure
      #traefik.http.middlewares.force-https.redirectscheme.scheme: https

      #- "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    #dynamic configuration
    labels:
      - "traefik.enable=true"
#      - "traefik.port=80"
#      - "traefik.docker.network=proxy"
      - "traefik.http.routers.proxy-part.tls=false"
#      - "traefik.http.services.proxy-part.loadbalancer.server.port=80"
#      traefik.tls.certificates.certFile: /usr/local/share/certificates/rwpc/janina.test+1.pem
#      traefik.tls.certificates.keyFile: /usr/local/share/ca-certificates/rwpc/janina.test+1-key.pem
      - "traefik.http.routers.proxy-part.rule=Host(`dash.janina.test`, `www.dash.janina.test`)"
      - "traefik.http.routers.proxy-part.service=api@internal"
      - "traefik.default.protocol=http"
      #traefik.http.routers.proxy-part.tls.domains.main: janina.test, www.janina.test
    ports:
      - "80:80"
#      - "8080:8080"
#      - "443:443"
    networks: 
      - proxy
    volumes: 
      #- /etc/traefik:/etc/traefik
      - ./.deploy/local/certificates:/usr/local/share/ca-certificates/rwpc:ro
      #- traefik_acme:/letsencrypt
      #ro - read only
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  proxy:
    #external: true
    driver: bridge

volumes:
  #traefik_acme:
  #  driver: local
  mysql:
    driver: local