name: 'Run Deploy Actions on push to main trigger'

on:
  push:
    branches:
      - 'main'

jobs:
  run-tests-on-pull-request:
    runs-on: [self-hosted, ubuntu, k8s]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JANINA_DOCKER_HUB_USER }}
          password: ${{ secrets.JANINA_DOCKER_HUB_ACCESS_KEY }}

      - name: Build Docker backend image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./vote_app_backend/
          tags: alonimacaroni/vote-backend:stage
          target: prod-stage

      - name: Build Docker frontend image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./frontend-ui/
          tags: alonimacaroni/vote-frontend:stage
          target: prod-stage

      - name: Set up S3cmd CLI Tool
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: digitalocean
          region: 'fra1'
          access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          secret_key: ${{ secrets.SPACES_SECRET_KEY }}

      - name: SSH to server
        run: |
          LOC=op ./devops.sh sshserver
          cd janina.devcon.team/

      - name: Start app
        run: |
          LOC=stage ./devops.sh 
          cd janina-voting-app/

      - name: Get .env from web spaces
        run: |
          s3cmd -c ~/.s3cfg get s3://janina-test-space/env-stage .env --force
          s3cmd -c ~/.s3cfg get s3://janina-test-space/env-backend-stage vote_app_backend/.env --force
          s3cmd -c ~/.s3cfg get s3://janina-test-space/env-frontend-stage frontend-ui/.env --force

      - name: Wait for DB Connection
        run: LOC=exec ./devops.sh wait

      - name: Run migrate command
        run: LOC=exec ./devops.sh migrate
      
      - name: Shutdown app
        run: LOC=exec ./devops.sh exitstage