name: 'Run pull-request tests'

# on:
#   pull_request:
on: [pull_request, push]

jobs:
  run-tests-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
   
      - name: Setup Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Set up S3cmd CLI Tool
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: digitalocean
          region: 'fra1'
          access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          secret_key: ${{ secrets.SPACES_SECRET_KEY }}

      - name: Get .env from web spaces
        run: |
          s3cmd -c ~/.s3cfg get s3://janina-test-space/env-ci .env --force
          s3cmd -c ~/.s3cfg get s3://janina-test-space/env-backend-ci vote_app_backend/.env --force

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JANINA_DOCKER_HUB_USER }}
          password: ${{ secrets.JANINA_DOCKER_HUB_ACCESS_KEY }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./vote_app_backend
          tags: alonimacaroni/vote-backend:ci
          target: dev-stage

      - name: Start app
        run: LOC=ci ./devops.sh start

      - name: Wait for DB Connection
        run: LOC=ci ./devops.sh wait

      - name: Run migrate command
        run: LOC=ci ./devops.sh migrate

      - name: Run tests against pull request
        run: LOC=ci ./devops.sh test
      
      - name: Shutdown app
        run: LOC=ci ./devops.sh exit

      - name: Clean Docker Environment
        run: ./devops.sh clean