name: 'Run pull-request tests'

on:
  pull_request:

jobs:
  run-tests-on-pull-request:
    runs-on: [self-hosted, ubuntu, k8s]
    steps:
      - name: before checkout
        run: pwd

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: after checkout
        run: pwd
      
      - name: Setup Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      
      - name: Update Ubuntu package repositories
        run: sudo apt-get update -y

      - name: Install GnuPG
        run: sudo apt-get install -y gnupg

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Decrypt .env.ci files
        run: |
          gpg --decrypt --output ./.env.ci --yes --passphrase '${{ secrets.PASSPHRASE }}' ./.env.ci.gpg
          gpg --decrypt --output ./vote_app_backend/.env.ci --yes --passphrase '${{ secrets.PASSPHRASE }}' ./vote_app_backend/.env.ci.gpg
          pwd
          ls -lah
          ls -lah ..

      - name: Show envs
        run: ls -lah

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./vote_app_backend/
          tags: alonimacaroni/backend-part:ci
          target: dev-stage

      - name: Run tests against pull request
        run: |
          LOC=ci ./devops.sh test
