name: Test pull-request and merge with main
on:
  pull_request:
    branches:
      - main
jobs:
  run-tests-on-pull-request:
    runs-on: [self-hosted, ubuntu, k8s]
    steps:
      - name: Run tests against pull request
        uses: actions/checkout@v3
        run: LOC=ci ./devops.sh test

      - name: Merge branch -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}

