name: Test pull-request and merge with main
on:
  pull_request:
    branches: [ main ]
jobs:
  run-tests-on-pull-request:
    runs-on: [self-hosted, ubuntu, k8s]
    steps:
      - name: Setup Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: Build Docker images
        run: |
          docker buildx build -t alonimacaroni/backend-part:ci --target dev-stage .

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests against pull request
        run: LOC=ci ./devops.sh test

      - name: Merge branch -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}

